### ISSUE TITLE
incorrectly "packaged" ...?

### ISSUE THREAD

**Issue by mesqueeb** [kouts/vue-dataset#51] opened 2021-12-14 03:18 UTC
not 100% sure yet what's causing this but Vite gives this error
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3253920/145926861-aa7257e6-c60d-4fd1-9071-999e39034864.png">

Vite might force packages to use `exports` in the package.json, but will research some more.

**Comment by mesqueeb** [comment] 2021-12-14 03:20
one related thread I found:
https://github.com/vitejs/vite/discussions/6013

**Comment by kouts** [comment] 2021-12-20 19:38
Hello @mesqueeb I have created a test repo here https://github.com/kouts/vue-dataset-next-import
it uses the latest version of Vite and an example of vue-dataset. 
It seems that `vue-dataset` seems to work ok with Vite so I couldn't reproduce the issue.
It could be something specific to your setup, can you please let me know so that I can close this?

**Comment by mesqueeb** [comment] 2021-12-20 23:36
@kouts Hmmm, that's odd, I wonder why it happened to me before.
Perhaps it's only in a monorepo setting. Or only in Vitepress. I can do some more digging.

In the meanwhile, please check the suggested way of defining the package.json is at the bottom of this page of the Vite docs:
https://vitejs.dev/guide/build.html#library-mode

other famous vue libraries like Vueuse now all also use this format for their exports:
https://github.com/vueuse/vueuse/blob/main/packages/core/package.json

**Comment by kouts** [comment] 2021-12-21 08:08
Thanks @mesqueeb I've checked the linked `docs`, it seems that there's not an explanation as to why this is recommended,
here are some more links for the `exports` property of `package.json`.
https://nodejs.org/api/packages.html#subpath-exports
https://webpack.js.org/guides/package-exports/

Meanwhile I have created a test repo for vue-dataset with Vite as well just to make sure there's no problem with the Vue 2 version.
You can find it here: https://github.com/kouts/vue-dataset-import

**Closed** 2022-01-22 15:04 UTC
